project:
  type: book
  render:  # only render index.qmd and .qmd files in chapters/
    - "index.qmd"
    - "chapters/*.qmd"
  execute-dir: project  # working directory is always root of project
  output-dir: "_build/"

book:
  # Metadata (fill this in):
  author:
    - "Nick Ulle"
  title: "DWR Statistics Workshops"
  description: "Reader for the DWR Statistics workshop series."
  repo-url: "https://github.com/ucdavisdatalab/dwr_workshop_statistics"
  site-url: "https://ucdavisdatalab.github.io/dwr_workshop_statistics"
  chapters:
    - "index.qmd"
    # List your chapters in order here.
    - part: "Exploring Data"
      chapters:
        - "chapters/exploring-data/index.qmd"
        - "chapters/exploring-data/getting-to-know-data.qmd"
        - "chapters/exploring-data/categorical-features.qmd"
        - "chapters/exploring-data/numerical-features.qmd"
        - "chapters/exploring-data/outliers.qmd"
        - "chapters/exploring-data/relationships-between-features.qmd"
        - "chapters/exploring-data/missing-values.qmd"
    - part: "Introduction to Applied Statistics"
      chapters:
        - "chapters/applied-statistics/index.qmd"
    - part: "Working with Temporal Data"
      chapters:
        - "chapters/temporal-data/index.qmd"
    - part: "Working with Censored Data"
      chapters:
        - "chapters/censored-data/index.qmd"
  appendices:
    - "chapters/references.qmd"
    - "chapters/assessment.qmd"

  # Formatting (be careful about changing these):
  date: now
  repo-actions: [issue, source]
  open-graph: true
  twitter-card: true
  favicon: "/images/logos/datalab-logo_square_150x150.png"
  image: "/images/logos/datalab-logo_opengraph_1200x630.png"
  image-alt: "The logo of the UC Davis DataLab."
  sidebar:
    logo: "/images/logos/datalab-logo-full-color-rgb.png"
    logo-alt: "The logo of the UC Davis DataLab."
    logo-href: "https://datalab.ucdavis.edu/"

format:
  html:
    theme: cosmo
    toc: true
    include-in-header:
      - text: |
          <style>
          .callout.callout-style-default .callout-body {
            padding: 0 1.5rem 0;
          }
          .cell-output-stdout {
            overflow-y: scroll;
            max-height: 30rem;
            margin-bottom: 0.75rem;
          }
          #quarto-sidebar a.text-start {
            margin-top: 1rem;
            font-weight: bold;
          }
          </style>
  # Uncomment to also generate a PDF:
  # pdf: default

# Uncomment to use BibTeX or BibLaTeX references:
bibliography: references.bib

# Cache computations from each chapter:
execute:
  freeze: auto
