<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Reader for the DWR Statistics workshop series.">

<title>3&nbsp; Numerical Features – DWR Statistics Workshops</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/exploring-data/outliers.html" rel="next">
<link href="../../chapters/exploring-data/categorical-features.html" rel="prev">
<link href="../..//images/logos/datalab-logo_square_150x150.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-4927f781319b8b164c3724fad35bda6c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
.callout.callout-style-default .callout-body {
  padding: 0 1.5rem 0;
}
.cell-output-stdout {
  overflow-y: scroll;
  max-height: 30rem;
  margin-bottom: 0.75rem;
}
#quarto-sidebar a.text-start {
  margin-top: 1rem;
  font-weight: bold;
}
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="3&nbsp; Numerical Features – DWR Statistics Workshops">
<meta property="og:description" content="Reader for the DWR Statistics workshop series.">
<meta property="og:image" content="https://ucdavisdatalab.github.io/dwr_workshop_statistics/chapters/exploring-data/numerical-features_files/figure-html/fig-total_nests_hist10-1.png">
<meta property="og:site_name" content="DWR Statistics Workshops">
<meta property="og:image:height" content="960">
<meta property="og:image:width" content="1344">
<meta name="twitter:title" content="3&nbsp; Numerical Features – DWR Statistics Workshops">
<meta name="twitter:description" content="Reader for the DWR Statistics workshop series.">
<meta name="twitter:image" content="https://ucdavisdatalab.github.io/dwr_workshop_statistics/chapters/exploring-data/numerical-features_files/figure-html/fig-total_nests_hist10-1.png">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/exploring-data/index.html">Exploring Data</a></li><li class="breadcrumb-item"><a href="../../chapters/exploring-data/numerical-features.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Features</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="https://datalab.ucdavis.edu/" class="sidebar-logo-link">
      <img src="../../images/logos/datalab-logo-full-color-rgb.png" alt="The logo of the UC Davis DataLab." class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="../../images/logos/datalab-logo-full-color-rgb.png" alt="The logo of the UC Davis DataLab." class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">DWR Statistics Workshops</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ucdavisdatalab/dwr_workshop_statistics" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Exploring Data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/exploring-data/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/exploring-data/getting-to-know-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting to Know the Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/exploring-data/categorical-features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical Features</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/exploring-data/numerical-features.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Features</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/exploring-data/outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Outliers</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/exploring-data/relationships-between-features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Relationships Between Features</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/exploring-data/missing-values.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Missing Values</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-binning-histograms" id="toc-sec-binning-histograms" class="nav-link active" data-scroll-target="#sec-binning-histograms"><span class="header-section-number">3.1</span> Binning and Histograms</a></li>
  <li><a href="#sec-density-plots" id="toc-sec-density-plots" class="nav-link" data-scroll-target="#sec-density-plots"><span class="header-section-number">3.2</span> Density Plots</a></li>
  <li><a href="#location-statistics" id="toc-location-statistics" class="nav-link" data-scroll-target="#location-statistics"><span class="header-section-number">3.3</span> Location Statistics</a>
  <ul class="collapse">
  <li><a href="#mode" id="toc-mode" class="nav-link" data-scroll-target="#mode"><span class="header-section-number">3.3.1</span> Mode</a></li>
  <li><a href="#sec-median" id="toc-sec-median" class="nav-link" data-scroll-target="#sec-median"><span class="header-section-number">3.3.2</span> Median</a></li>
  <li><a href="#sec-mean" id="toc-sec-mean" class="nav-link" data-scroll-target="#sec-mean"><span class="header-section-number">3.3.3</span> Mean</a></li>
  </ul></li>
  <li><a href="#sec-scale-statistics" id="toc-sec-scale-statistics" class="nav-link" data-scroll-target="#sec-scale-statistics"><span class="header-section-number">3.4</span> Scale Statistics</a>
  <ul class="collapse">
  <li><a href="#sec-interquartile-range" id="toc-sec-interquartile-range" class="nav-link" data-scroll-target="#sec-interquartile-range"><span class="header-section-number">3.4.1</span> Interquartile Range</a></li>
  <li><a href="#sec-standard-deviation" id="toc-sec-standard-deviation" class="nav-link" data-scroll-target="#sec-standard-deviation"><span class="header-section-number">3.4.2</span> Standard Deviation</a></li>
  </ul></li>
  <li><a href="#a-final-note" id="toc-a-final-note" class="nav-link" data-scroll-target="#a-final-note"><span class="header-section-number">3.5</span> A Final Note</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ucdavisdatalab/dwr_workshop_statistics/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/ucdavisdatalab/dwr_workshop_statistics/blob/main/chapters/exploring-data/numerical-features.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/exploring-data/index.html">Exploring Data</a></li><li class="breadcrumb-item"><a href="../../chapters/exploring-data/numerical-features.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Features</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-numerical-features" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Numerical Features</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled" title="Learning Goals">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Learning Goals
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>After this lesson, you should be able to:</p>
<ul>
<li>Use binning to turn numerical features into categorical features</li>
<li>Create and interpret histograms of numerical features</li>
<li>Create and interpret density plots of numerical features</li>
<li>Describe several different ways to define location and scale</li>
<li>Explain the location statistics mode, median, and mean</li>
<li>Explain the scale statistics IQR and standard deviation</li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Required Packages">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Required Packages
</div>
</div>
<div class="callout-body-container callout-body">
<p>This chapter uses the following R packages:</p>
<ul>
<li>dplyr</li>
<li>ggplot2</li>
</ul>
<p>For a refresher about how to install and load packages, see the <a href="https://ucdavisdatalab.github.io/dwr_workshop_r_basics/chapters/getting-started/getting-started.html#sec-packages">Packages</a> section of DataLab’s R Basics workshop reader.</p>
</div>
</div>
<p>Whether the features we’re exploring are categorical (<a href="categorical-features.html" class="quarto-xref"><span>Chapter 2</span></a>) or numerical, what we ultimately want to understand is the distribution (<a href="categorical-features.html#sec-distributions" class="quarto-xref"><span>Section 2.4</span></a>): how values are spread out across the range of possible values, which values are common, and which are rare.</p>
<p>The values of a numerical feature are numbers, so in addition to calculating how frequently they occur, we can also calculate how far apart they are. In other words, we can use math to summarize numerical features in ways that aren’t possible for categorical features.</p>
<section id="sec-binning-histograms" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-binning-histograms"><span class="header-section-number">3.1</span> Binning and Histograms</h2>
<p>If we compute frequencies for a numerical feature, we run into a problem: most of the frequencies are 1, because most of the values are distinct. As a consequence, it’s hard to tell whether there are patterns in the distribution from the frequencies alone. <a href="categorical-features.html#fig-total_nests_bar" class="quarto-xref">Figure&nbsp;<span>2.3</span></a> (and the associated frequency table) demonstrates this problem.</p>
<p>One way to address the problem is by grouping values that are nearby each other, a process called <strong>binning</strong>, and then computing frequencies for the groups. Think of binning as slicing up the range of possible values into a few pieces, called <strong>bins</strong>. Binning turns a numerical feature into a categorical feature, so that we can use the methods from <a href="categorical-features.html" class="quarto-xref"><span>Chapter 2</span></a>.</p>
<p>When we bin a feature, we have to make choices about how many bins to use and where their endpoints are. Different choices can lead to different conclusions, so in an analysis that uses binning, it’s important to investigate several choices and discuss how the conclusions change. To make comparisons between bins fair, we’ll often chose bins that have equal widths, although whether this really leads to fair comparisons depends on the nature of the data—think it through carefully!</p>
<p>A <strong>histogram</strong> is a bar plot where the values on the x-axis are binned. Since there are no gaps between the bins, in a histogram there are no gaps between the bars.</p>
<p>We can use R to bin data and make a histogram automatically. We strongly recommend setting the bin width manually (and this is also what the ggplot2 documentation recommends). For example, here’s how to make a histogram for the <code>total_nests</code> column with 10-nest bins:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns) <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> total_nests) <span class="sc">+</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Set color = "black" to outline the bars, for better legibility.</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-total_nests_hist10" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-total_nests_hist10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-total_nests_hist10-1.png" id="fig-total_nests_hist10" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-total_nests_hist10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1
</figcaption>
</figure>
</div>
</div>
</div>
<p>This is a bit clearer than the bar plot in <a href="categorical-features.html#fig-total_nests_bar" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>, because now we can read the count for the 0 bin, whereas in the bar plot, the count for 0 was obscured. That said, there are still a lot of bars, so let’s try a wider bin width:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> total_nests) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">100</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-total_nests_hist100" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-total_nests_hist100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-total_nests_hist100-1.png" id="fig-total_nests_hist100" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-total_nests_hist100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that this histogram has fewer sudden jumps and drops than the previous one (<a href="#fig-total_nests_hist10" class="quarto-xref">Figure&nbsp;<span>3.1</span></a>). Increasing bin width has a smooting effect, making large-scale trends easier to see but fine details harder to see.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>When you bin a feature (whether for a histogram or some other purpose), always check several different binning strategies, because they might lead to different conclusions. Point out and explain the discrepancies when you share the results. This is a form of statistical due diligence.</p>
</div>
</div>
<p>A histogram is usually more appropriate than a bar plot for visualizing features that represent a continuous quantity, even if they measure it in a discrete way, because there are no gaps between the bars. For instance, the <code>year</code> feature is discrete, but it measures time, which we usually think of as continuous. We can make a histogram without binning by setting the bin width to 1:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> year) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-year_hist1" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-year_hist1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-year_hist1-1.png" id="fig-year_hist1" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-year_hist1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.3
</figcaption>
</figure>
</div>
</div>
</div>
<p>Compared to the bar plot <a href="categorical-features.html#fig-year_bar" class="quarto-xref">Figure&nbsp;<span>2.2</span></a>, the histogram makes it clear that each bar spans an entire year.</p>
<p>There’s no need to bin the <code>year</code> feature, and in this case, the smoothing effect of binning actually makes it harder to interpret:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> year) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-year_hist2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-year_hist2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-year_hist2-1.png" id="fig-year_hist2" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-year_hist2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.4
</figcaption>
</figure>
</div>
</div>
</div>
<p>With 2-year bins, the drop in 2018 is still visible, but it’s hard to tell exactly which year has the drop (is it 2018 or 2019 or both?). Other details are also obscured.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>R’s functions for making histograms assume numerical data, but we can make a histogram for ordinal data in two steps, by first binning and then making a bar plot.</p>
<p>R’s <code>cut</code> function bins data (without making a histogram).</p>
</div>
</div>
</section>
<section id="sec-density-plots" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="sec-density-plots"><span class="header-section-number">3.2</span> Density Plots</h2>
<p>Binning and histograms help us understand the shape of the distribution of a numerical feature, but there’s still a problem. For continuous features, histograms can overstate differences in frequency from one bin to the next, because the edge of the bin is a sharp dividing line. We can remedy this by blurring or smoothing the divisions between bins.</p>
<p>A <strong>density</strong> is a function that represents the shape of a distribution. Think of a density as a smooth curve that traces the tops of the bars in a histogram. A <strong>density plot</strong> is a plot that shows a density. Compared to a histogram, the divisions between the bins are no longer visible, but the pattern of the tops of the bars still is.</p>
<p>We can use R and ggplot2 to draw a density plot. Here’s a density plot for the <code>total_nests</code> feature:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> total_nests) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-total_nests_density" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-total_nests_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-total_nests_density-1.png" id="fig-total_nests_density" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-total_nests_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that the trends from <a href="#fig-total_nests_hist10" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> are still present. The density is high near 0, drops off quickly, and then has a long tail with a few small peaks.</p>
<p>Although the density plot has the same shape as the histogram, the quantity on the y-axis is not counts or frequencies. Instead, we scale the density curve the that total area underneath it is 1 or 100%. This is because the area under any part of the density is an estimate of the probability of randomly drawing the corresponding values on the x-axis.</p>
<p>Mathematically, we estimate a density by putting a small, smooth “bump” function, called a <strong>kernel</strong>, at each observed value of the feature and then adding all of these up. How much the bump spreads out, called the <strong>bandwidth</strong>, is a bit like a bin width, with larger bandwidths leading to smoother densities.</p>
<p>When we make a density plot, R uses a statistical formula to compute a default bandwidth. The default bandwidth often strikes a good balance between showing coarse trends and fine details. We can change the bandwidth through the <code>adjust</code> parameter, which is multiplied by the default (so <code>adjust = 0.5</code> means half of the default). This way the bandwidth is still estimated from and on a similar scale as the data. Here’s the density plot for <code>total_nests</code> with a smaller bandwidth:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> total_nests) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">adjust =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-total_nests_density0.5" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-total_nests_density0.5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-total_nests_density0.5-1.png" id="fig-total_nests_density0.5" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-total_nests_density0.5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.6
</figcaption>
</figure>
</div>
</div>
</div>
<p>And here it is with a larger bandwidth:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> total_nests) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">adjust =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-total_nests_density2" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-total_nests_density2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-total_nests_density2-1.png" id="fig-total_nests_density2" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-total_nests_density2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.7
</figcaption>
</figure>
</div>
</div>
</div>
<p>Decreasing the bandwidth makes the density rougher, while increasing it makes it smoother. As with bin width for histograms, it’s important to try different bandwidths for density plots, since different amounts of smoothing can lead to different conclusions.</p>
<p>The lack of bin edges in density plots can make them easier to read than histograms, but an important limitation to keep in mind is that density plots are a kind of estimate, and as a consequence, they’re sensitive to the number of observations in the dataset. For a dataset with a relatively small number of observations (for example, less than 30), a histogram or bar plot is a more faithful representation.</p>
<p>Density plots are especially helpful for comparing how a feature is distributed across multiple groups, because we can display all of the densities in a single plot. Let’s try this for the <code>total_nests</code> feature by using the regions from <code>region_3</code> as groups. We’ll first filter out the unexpected regions Arizona, Kings, and Sacramento, because they have low numbers of observations. Here’s the plot:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>EXPECTED_REGION_3 <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"S.F._BAY"</span>, <span class="st">"CENTRAL"</span>, <span class="st">"SOUTHERN"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>terns_region <span class="ot">=</span> <span class="fu">filter</span>(terns, region_3 <span class="sc">%in%</span> EXPECTED_REGION_3)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(terns_region) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> total_nests, <span class="at">color =</span> region_3) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 8 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-total_nests_region_3_density" class="quarto-float quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-total_nests_region_3_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="numerical-features_files/figure-html/fig-total_nests_region_3_density-1.png" id="fig-total_nests_region_3_density" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-total_nests_region_3_density-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.8
</figcaption>
</figure>
</div>
</div>
</div>
<p>This reveals that the nest counts for Central tend to be low in comparison to S.F. Bay and Southern. Curiously, a substantial proportion of nest counts for S.F. Bay are between 250 and 500. This could mean that there are sites in the S.F. Bay region that are sufficiently well-protected that large flocks of terns use them every year, whereas other sites see varying numbers of birds each year, depending on their condition. There’s certainly more we could hypothesize based on the plot and investigate further using other features. This is an example of exploring two features simultaneously, which we’ll learn more about in <a href="relationships-between-features.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
</section>
<section id="location-statistics" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="location-statistics"><span class="header-section-number">3.3</span> Location Statistics</h2>
<p>So far, we’ve only used visualizations to summarize numerical features. In some cases, we might also want to use quantitative summaries. We’ll focus on quantities that attempt to answer two questions about a feature’s distribution:</p>
<ol type="1">
<li>What is the <strong>location</strong> of the data? For 1-dimensional data, where are most of the observations on the number line? For higher-dimensional data, where are most of the observations in the space?</li>
<li>What is the <strong>scale</strong> of the data? In other words, how much do the observations spread out?</li>
</ol>
<p>We can also ask other questions about the distribution, such as how many peaks it has and whether it’s symmetrical around some central point, but these are often easier to answer with visualizations. Asking about location and scale is a sensible starting point.</p>
<p>The questions leave how to quantify location and scale open to interpretation, but there are a few widely-used and well-studied choices. The remainder of this section introduces location statistics, and <a href="#sec-scale-statistics" class="quarto-xref"><span>Section 3.4</span></a> introduces scale statistics.</p>
<p>To help develop intuition, we’ll use this small, artificial “toy” dataset in several examples:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>toy <span class="ot">=</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We’ll also use the <code>total_nests</code> feature from the California least terns dataset. Recall the density plot for the feature (<a href="#fig-total_nests_density" class="quarto-xref">Figure&nbsp;<span>3.5</span></a>). Where would you say the distribution is located, if you had to pick just one point?</p>
<section id="mode" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="mode"><span class="header-section-number">3.3.1</span> Mode</h3>
<p>First, let’s think of location as the value that occurs most frequently. This is the mode, which we introduced for categorical features in <a href="categorical-features.html#sec-mode" class="quarto-xref"><span>Section 2.4.1</span></a>. For continuous features, the mode is at the tallest peak of the density curve. Values at or near the mode occur more frequently than any others.</p>
<p>For the toy dataset, the mode is -1, because it occurs more than any of the other values. If we didn’t want to count ourselves, we could compute this with the <code>table</code> function.</p>
<p>For <code>total_nests</code>, the mode is at or close to 0, depending on whether we treat the feature as discrete and estimate with the frequencies or treat it as continuous and estimate with the density curve.</p>
<p>An advantage of the mode is that we can compute it for any type of feature, categorical or numerical.</p>
<p>The mode also has some disadvantages. The mode might occur only slightly more often than other values, and it might be far away from many other values that can occur. The latter is certainly the case for <code>total_nests</code>, where the mode is 0 but some of the values exceed 1,500.</p>
</section>
<section id="sec-median" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="sec-median"><span class="header-section-number">3.3.2</span> Median</h3>
<p>Next, let’s think of location as the midpoint of the values. In other words, we’ll sort the values and find the one in the middle. This statistic is called the <strong>median</strong>.</p>
<p>In R, the <code>median</code> function computes the median of a feature. For the toy dataset, the median is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(toy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1</code></pre>
</div>
</div>
<p>This means half of the observed values are less than or equal to -1 and half are greater than or equal. By coincidence, the median is the same as the mode. So -1 also occurs more frequently than any other value.</p>
<p>For <code>total_nests</code>, the median is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(terns<span class="sc">$</span>total_nests, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 42</code></pre>
</div>
</div>
<p>It’s meaningful that the median is larger than the mode (0). The median tells us half of the observed values of <code>total_nests</code> are less than or equal to 42 and half are greater than or equal. Even though the mode is more common than any other value, if we only paid attention to it, we’d be ignoring more than half of the observed values!</p>
<div class="callout callout-style-default callout-note callout-titled" title="Note: Removing Missing Values">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: Removing Missing Values
</div>
</div>
<div class="callout-body-container callout-body">
<p>Most statistical summary functions in R provide an <code>na.rm</code> parameter to control whether missing values are removed before computing the statistic. By default, it’s <code>FALSE</code> and missing values are kept. Set <code>na.rm = TRUE</code> to remove the missing values. This is useful for quick, initial investigations of a dataset.</p>
<p>In a complete analysis, you should think carefully about what the missing values mean, whether they exhibit any patterns, and whether there are enough non-missing values for statistical summaries to be good representatives of the data. We’ll learn more about this in <a href="missing-values.html" class="quarto-xref"><span>Chapter 6</span></a>.</p>
</div>
</div>
<p>Another name for the median is the <strong>50th percentile</strong>, because the median is greater than roughly 50% of the values. We can also estimate other percentiles. For instance, the 25th percentile is the value one-quarter of the way through the sorted data. <strong>Quantile</strong> is another word for percentile.</p>
<p>In R, we can compute percentiles with the <code>quantile</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(toy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
  -2   -1   -1    1    6 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(terns<span class="sc">$</span>total_nests, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
   0    5   42  164 1741 </code></pre>
</div>
</div>
<p>Statisticians call the median a <strong>robust</strong> statistic, because it’s not affected much by extreme (very small or very large) values. For example, if we change the largest value 6 in the toy dataset to 1,000,000, the median stays the same:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>toy2 <span class="ot">=</span> toy</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>toy2[<span class="fu">match</span>(<span class="dv">6</span>, toy2)] <span class="ot">=</span> <span class="dv">1000000</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(toy2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1</code></pre>
</div>
</div>
<p>Likewise, if we put a new value, 100, in the dataset, the median only increases slightly:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>toy2 <span class="ot">=</span> <span class="fu">c</span>(toy2, <span class="dv">100</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(toy2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.5</code></pre>
</div>
</div>
<p>Robustness is a useful property because extremes rarely represent a majority of the data—that’s why they’re extremes. Sometimes extreme values can even be erroneous, but the median is relatively unaffected.</p>
<p>The cost of robustness is that the median uses information less efficiently than the next statistic we’ll learn about (<a href="#sec-mean" class="quarto-xref"><span>Section 3.3.3</span></a>). To see this, think about how we compute the median: we only use the values in the middle, but the other values might also contain important information.</p>
</section>
<section id="sec-mean" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="sec-mean"><span class="header-section-number">3.3.3</span> Mean</h3>
<p>Finally, let’s think of location as a balancing point for the values. Imagine trying to balance the distribution (picture a density plot, such as <a href="#fig-total_nests_density" class="quarto-xref">Figure&nbsp;<span>3.5</span></a>) on a triangular wedge. Where would you have to place the wedge? This statistic is called the <strong>mean</strong> or <strong>average</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Definition: Sample Mean">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Sample Mean
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mathematically, for data <span class="math inline">\(x_1, x_2, \dots, x_n\)</span>, the sample mean <span class="math inline">\(\bar{x}\)</span> is defined as <span class="math display">\[
\begin{align*}
\bar{x}
&amp;= \frac{1}{n} (x_1 + x_2 + \dots + x_n) \\
&amp;= \frac{1}{n} \sum_{i=1}^n x_i \\
\end{align*}
\]</span></p>
<p>In words, we add up all of the values and then divide by the number of values.</p>
<p>Statisticians conventionally write an overbar to indicate a sample mean, as in <span class="math inline">\(\bar{x}\)</span>. They write the unknown population mean, which is estimated by the sample mean, as the <a href="https://en.wikipedia.org/wiki/Greek_letters_used_in_mathematics,_science,_and_engineering">Greek letter</a> <span class="math inline">\(\mu\)</span>.</p>
</div>
</div>
<p>In R, the <code>mean</code> function computes the mean of a feature. For the toy dataset, the mean is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(toy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4285714</code></pre>
</div>
</div>
<p>Notice that the mean is quite a bit larger than the median (-1). This is because of the value 6, which is relatively far from the other values and thus exerts a lot of influence (in the balancing metaphor, it has a lot of leverage).</p>
<p>For <code>total_nests</code>, the mean is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(terns<span class="sc">$</span>total_nests, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 162.8455</code></pre>
</div>
</div>
<p>Once again, the mean is larger than than the median (42). As we saw in the density plot (<a href="#fig-total_nests_density" class="quarto-xref">Figure&nbsp;<span>3.5</span></a>), the <code>total_nests</code> feature contains a few very large values. These don’t affect the median much, but they do affect on the mean.</p>
<p>The mean is good for getting a general idea of where the center of the data is. It’s more efficient than the median for this purpose, because it takes all of the data into account.</p>
<p>On the other hand, the mean is sensitive to extreme values, especially in comparison to the median. If the mean seems unexpectedly small or large, check for extreme values.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>We recommend using the mean and median together to get the best of both. Comparing the mean and median can provide insight into how asymmetric the distribution is. For instance, if the mean is much larger than the median, then the distribution likely has a long right tail. Of course, a visualization is still generally a better summary than any number of statistics.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Note: Other Means">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Note: Other Means
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are other ways to define the mean, with different advantages and disadvantages.</p>
<p>The mean defined in this section is formally called the <strong>arithmetic mean</strong>. The arithmetic mean is well-suited to values that can be combined naturally by adding, such as physical measurements (length, weight, etc.) and counts.</p>
<p>To learn more about other ways to define the mean, see <a href="https://meancalculator.com/choosing-right-mean.html">How to Choose the Right Mean for Your Data</a> from <span class="citation" data-cites="mean-calculator">Pul et al. (<a href="../references.html#ref-mean-calculator" role="doc-biblioref">2026</a>)</span>.</p>
</div>
</div>
</div>
</section>
</section>
<section id="sec-scale-statistics" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="sec-scale-statistics"><span class="header-section-number">3.4</span> Scale Statistics</h2>
<p>The scale of a distribution refers to how spread out its values are. As with location, there are many different ways to define scale and thus many different statistics. We’ll focus on two popular scale statistics.</p>
<section id="sec-interquartile-range" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="sec-interquartile-range"><span class="header-section-number">3.4.1</span> Interquartile Range</h3>
<p>One way to think about the scale of a distribution is as the distance between its tails. If we take a representative value from each tail, we can compute the distance between them by subtracting. The question is: which values should we choose?</p>
<p>The minimum and maximum might seem tempting, since they’re the farthest along each tail. But that becomes a problem if most of the data lie close to the center, with the minimum and maximum among just a few extreme values. By using them, we’d overestimate how much the data spread out. The minimum and maximum can also vary substantially from one sample to the next, which means our scale estimates could as well—they’d be unreliable for estimating the scale of the population.</p>
<p>A better choice is something near the tails but less sensitive to extremes. <a href="#sec-median" class="quarto-xref"><span>Section 3.3.2</span></a> explained that the median is robust, meaning it’s mostly unaffected by extreme values. It turns out most other percentiles are also relatively robust. We can use the distance between the 75th and 25th percentile as a robust estimator for scale. Conveniently, we can also interpret this as the width of the middle 50% of the data.</p>
<p>The 25th, 50th, and 75th percentiles are called <strong>quartiles</strong> (with an “r”) because they separate the data into four parts (hence “quart-”). So the distance between the 75th and and 25th percentile is called the <strong>interquartile range</strong> (IQR).</p>
<p>In R, the <code>IQR</code> function computes the IQR of a feature. For the toy dataset, the IQR is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(toy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>As a reminder, the dataset looks like this:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>toy</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2 -1 -1 -1  0  2  6</code></pre>
</div>
</div>
<p>And the quartiles are:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(toy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
  -2   -1   -1    1    6 </code></pre>
</div>
</div>
<p>The IQR is 2 because the 25th percentile is -1 and the 75th percentile is 1. The middle 50% of the data is 2 units wide.</p>
<p>As we mentioned, IQR is relatively unaffected by extreme values. If we change the largest value 6 in the toy dataset to 1,000,000, the IQR stays the same. The IQR has the same tradeoffs as the median: it’s a robust estimator of scale, but it’s less efficient than estimators that use all of the data.</p>
<p>For <code>total_nests</code>, the IQR is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>(terns<span class="sc">$</span>total_nests, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 159</code></pre>
</div>
</div>
<p>This means the middle 50% of the data is 159 nests wide. We can gain a better understanding of the scale by examining the quartiles, too:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(terns<span class="sc">$</span>total_nests, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
   0    5   42  164 1741 </code></pre>
</div>
</div>
<p>Notice that the 25th percentile is closer to the median than the 75th percentile. The large IQR shows that the data are very spread out; the quartiles show that most of that spread is in the right tail. In other words, the distribution is asymmetrical, as we saw in <a href="#fig-total_nests_density" class="quarto-xref">Figure&nbsp;<span>3.5</span></a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Visualizations are almost always the best way to study distributions. If you can’t make a visualization, examine multiple statistics rather than just one. A lone statistic is unable to capture nuance and can even be misleading.</p>
</div>
</div>
</section>
<section id="sec-standard-deviation" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="sec-standard-deviation"><span class="header-section-number">3.4.2</span> Standard Deviation</h3>
<p>Another way to think about scale is as the typical distance from any value to the center of the distribution. This interpretation raises three questions:</p>
<ol type="1">
<li>What do we mean by “typical” distance?</li>
<li>How do we measure distance?</li>
<li>What do we mean by the “center” of the distribution?</li>
</ol>
<p>As usual, different answers to these questions lead to different statistics. For our purposes, we’ll say:</p>
<ol type="1">
<li>Typical distance is mean distance.</li>
<li>We measure distance as the squared difference. Squaring ensures that the distances are non-negative.</li>
<li>The center of the distribution is the sample mean.</li>
</ol>
<p>The difference between a point and a mean is called a <strong>deviation</strong>. If we square the deviations and compute their mean, the result is called the <strong>variance</strong> and is measured in squared units. To get back to the original units, we can take a square root of the variance. This is called the <strong>standard deviation</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Definition: Sample Variance and Sample Standard Deviation">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Definition: Sample Variance and Sample Standard Deviation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mathematically, for data <span class="math inline">\(x_1, x_2, \dots, x_n\)</span> with sample mean <span class="math inline">\(\bar{x}\)</span> (<a href="#sec-mean" class="quarto-xref"><span>Section 3.3.3</span></a>), the sample variance <span class="math inline">\(s^2\)</span> is defined as</p>
<p><span class="math display">\[
\begin{align*}
s^2
&amp;= \frac{1}{n-1} \left[
  (x_1 - \bar{x})^2 + (x_2 - \bar{x})^2 + \dots + (x_n - \bar{x})^2
\right] \\
&amp;= \frac{1}{n-1} \sum_{i=0}^n (x_i - \bar{x})^2 \\
\end{align*}
\]</span></p>
<p>In words, we compute the mean of the squared distances to the sample mean. We divide by <span class="math inline">\(n - 1\)</span> rather than <span class="math inline">\(n\)</span> as a statistical correction for the fact that <span class="math inline">\(\bar{x}\)</span> is also an estimator.</p>
<p>The sample standard deviation <span class="math inline">\(s\)</span> is defined as the square root of the variance <span class="math inline">\(s^2\)</span>.</p>
<p>Statisticians conventionally write the unknown population variance, which is estimated by the sample variance, as <span class="math inline">\(\sigma^2\)</span>. Thus they write the unknown population standard deviation as <span class="math inline">\(\sigma\)</span>.</p>
</div>
</div>
<p>Think of the standard deviation as the average distance from a value to the mean. Larger standard deviations mean the data are more spread out. As a rule of thumb, most of the data will be within 3 standard deviations of the mean.</p>
<p>In R, the <code>sd</code> function computes the standard deviation of a feature. For the toy dataset, the standard deviation is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(toy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.760262</code></pre>
</div>
</div>
<p>This means that on average, values are about 2.76 units from the mean 0.43. That’s roughly consistent with the range of values in the toy dataset.</p>
<p>For <code>total_nests</code>, the standard deviation is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(terns<span class="sc">$</span>total_nests, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 293.1786</code></pre>
</div>
</div>
<p>This means that on average, the number of nests is 162 (the mean) plus or minus 293. We know the number of nests can’t be negative, so the lower bound is actually 0. The large standard deviation reflects both the numerous 0 values on the left and the very large values on the right.</p>
<p>The standard deviation and IQR are analogous to the mean and median, respectively. The standard deviation is not robust, but uses the available data more efficiently. We recommend examining both.</p>
</section>
</section>
<section id="a-final-note" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="a-final-note"><span class="header-section-number">3.5</span> A Final Note</h2>
<p>The <code>summary</code> function computes a detailed statistical summary of an R object. For instance, here’s the summary for the <code>total_nests</code> column:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(terns<span class="sc">$</span>total_nests)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
    0.0     5.0    42.0   162.8   164.0  1741.0       8 </code></pre>
</div>
</div>
<p>For data frames, the <code>summary</code> function computes a summary of each column, guessing an appropriate statistic based on the column’s data type:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(terns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      year       site_name         site_name_2013_2018 site_name_1988_2001
 Min.   :2000   Length:791         Length:791          Length:791         
 1st Qu.:2008   Class :character   Class :character    Class :character   
 Median :2013   Mode  :character   Mode  :character    Mode  :character   
 Mean   :2013                                                             
 3rd Qu.:2018                                                             
 Max.   :2023                                                             
                                                                          
  site_abbr           region_3           region_4            event          
 Length:791         Length:791         Length:791         Length:791        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
     bp_min           bp_max           fl_min            fl_max       
 Min.   :   0.0   Min.   :   0.0   Min.   :   0.00   Min.   :   0.00  
 1st Qu.:   3.0   1st Qu.:   5.0   1st Qu.:   0.00   1st Qu.:   0.00  
 Median :  30.0   Median :  38.0   Median :   7.00   Median :   9.00  
 Mean   : 129.3   Mean   : 151.0   Mean   :  40.82   Mean   :  50.35  
 3rd Qu.: 127.5   3rd Qu.: 148.5   3rd Qu.:  38.00   3rd Qu.:  47.50  
 Max.   :1691.0   Max.   :1691.0   Max.   :1025.00   Max.   :1145.00  
 NA's   :8        NA's   :8        NA's   :12        NA's   :12       
  total_nests      nonpred_eggs    nonpred_chicks      nonpred_fl     
 Min.   :   0.0   Min.   :  0.00   Min.   :   0.00   Min.   :  0.000  
 1st Qu.:   5.0   1st Qu.:  2.00   1st Qu.:   0.00   1st Qu.:  0.000  
 Median :  42.0   Median : 12.00   Median :   3.00   Median :  0.000  
 Mean   : 162.8   Mean   : 60.29   Mean   :  44.37   Mean   :  4.181  
 3rd Qu.: 164.0   3rd Qu.: 69.00   3rd Qu.:  22.00   3rd Qu.:  2.000  
 Max.   :1741.0   Max.   :748.00   Max.   :1063.00   Max.   :207.000  
 NA's   :8        NA's   :164      NA's   :198       NA's   :240      
   nonpred_ad     pred_control         pred_eggs       pred_chicks     
 Min.   : 0.000   Length:791         Min.   :  0.00   Min.   :  0.000  
 1st Qu.: 0.000   Class :character   1st Qu.:  2.00   1st Qu.:  0.000  
 Median : 0.000   Mode  :character   Median :  6.50   Median :  2.000  
 Mean   : 0.851                      Mean   : 41.57   Mean   :  8.519  
 3rd Qu.: 1.000                      3rd Qu.: 25.50   3rd Qu.:  7.500  
 Max.   :22.000                      Max.   :417.00   Max.   :149.000  
 NA's   :234                         NA's   :737      NA's   :737      
    pred_fl          pred_ad       pred_pefa         pred_coy_fox      
 Min.   : 0.000   Min.   : 0.00   Length:791         Length:791        
 1st Qu.: 0.000   1st Qu.: 0.00   Class :character   Class :character  
 Median : 0.000   Median : 0.50   Mode  :character   Mode  :character  
 Mean   : 2.365   Mean   : 2.69                                        
 3rd Qu.: 2.000   3rd Qu.: 2.00                                        
 Max.   :23.000   Max.   :41.00                                        
 NA's   :739      NA's   :733                                          
  pred_meso         pred_owlspp        pred_corvid        pred_other_raptor 
 Length:791         Length:791         Length:791         Length:791        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
 pred_other_avian    pred_misc           total_pefa     total_coy_fox    
 Length:791         Length:791         Min.   : 0.000   Min.   :  0.000  
 Class :character   Class :character   1st Qu.: 0.000   1st Qu.:  0.000  
 Mode  :character   Mode  :character   Median : 0.000   Median :  0.000  
                                       Mean   : 1.741   Mean   :  9.464  
                                       3rd Qu.: 0.000   3rd Qu.:  0.000  
                                       Max.   :34.000   Max.   :348.000  
                                       NA's   :737      NA's   :735      
   total_meso       total_owlspp     total_corvid     total_other_raptor
 Min.   :  0.000   Min.   : 0.000   Min.   :  0.000   Min.   : 0.000    
 1st Qu.:  0.000   1st Qu.: 0.000   1st Qu.:  0.000   1st Qu.: 0.000    
 Median :  0.000   Median : 0.000   Median :  0.000   Median : 0.000    
 Mean   :  5.556   Mean   : 1.455   Mean   :  7.962   Mean   : 1.712    
 3rd Qu.:  0.000   3rd Qu.: 0.500   3rd Qu.:  2.000   3rd Qu.: 1.000    
 Max.   :244.000   Max.   :41.000   Max.   :177.000   Max.   :43.000    
 NA's   :737       NA's   :736      NA's   :739       NA's   :739       
 total_other_avian   total_misc      first_observed     last_observed     
 Min.   :  0.000   Min.   :  0.000   Length:791         Length:791        
 1st Qu.:  0.000   1st Qu.:  0.000   Class :character   Class :character  
 Median :  0.000   Median :  0.000   Mode  :character   Mode  :character  
 Mean   :  8.898   Mean   :  6.566                                        
 3rd Qu.:  2.000   3rd Qu.:  0.000                                        
 Max.   :140.000   Max.   :168.000                                        
 NA's   :742       NA's   :738                                            
  first_nest        first_chick        first_fledge      
 Length:791         Length:791         Length:791        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         </code></pre>
</div>
</div>
<p>These summaries are useful as a quick overview of an entire dataset. We strongly recommend following up with visualizations to develop a more nuanced understanding of individual features and their distributions.</p>
<div class="callout callout-style-default callout-note callout-titled" title="See Also">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>See Also
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="https://en.wikipedia.org/wiki/Anscombe%27s_quartet">Anscombe’s Quartet</a> <span class="citation" data-cites="anscombe1973">(<a href="../references.html#ref-anscombe1973" role="doc-biblioref">Anscombe 1973</a>)</span> and the <a href="https://www.research.autodesk.com/publications/same-stats-different-graphs/">Datasaurus Dozen</a> <span class="citation" data-cites="datasaurus">(<a href="../references.html#ref-datasaurus" role="doc-biblioref">Matejka and Fitzmaurice 2017</a>)</span> are two datasets that exemplify the importance of making visualizations. For these datasets, statistics alone lead to completely incorrect conclusions.</p>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-anscombe1973" class="csl-entry" role="listitem">
Anscombe, F. J. 1973. <span>“Graphs in Statistical Analysis.”</span> <em>The American Statistician</em> 27 (1): 17–21. <a href="https://doi.org/10.1080/00031305.1973.10478966">https://doi.org/10.1080/00031305.1973.10478966</a>.
</div>
<div id="ref-datasaurus" class="csl-entry" role="listitem">
Matejka, Justin, and George Fitzmaurice. 2017. <span>“Same Stats, Different Graphs: Generating Datasets with Varied Appearance and Identical Statistics Through Simulated Annealing.”</span> <em>Proceedings of the 2017 <span>CHI</span> Conference on Human Factors in Computing Systems</em> (New York, <span>NY</span>, <span>USA</span>), <span>CHI</span> ’17, May 2, 1290–94. <a href="https://doi.org/10.1145/3025453.3025912">https://doi.org/10.1145/3025453.3025912</a>.
</div>
<div id="ref-mean-calculator" class="csl-entry" role="listitem">
Pul, Ruurtjan, Peter Troshin, and Svetlana Fomina. 2026. <span>“Mean Calculator.”</span> <a href="https://meancalculator.com/">https://meancalculator.com/</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ucdavisdatalab\.github\.io\/dwr_workshop_statistics");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/exploring-data/categorical-features.html" class="pagination-link" aria-label="Categorical Features">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical Features</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/exploring-data/outliers.html" class="pagination-link" aria-label="Outliers">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Outliers</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ucdavisdatalab/dwr_workshop_statistics/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li><li><a href="https://github.com/ucdavisdatalab/dwr_workshop_statistics/blob/main/chapters/exploring-data/numerical-features.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div></div></footer></body></html>