# Hypothesis Tests

::: {.callout-note title="Learning Goals" collapse="false"}
After this lesson, you should be able to:

* TODO
:::

:::{.callout-important title="Required Packages"}
This chapter uses the following R packages:

* dplyr
* ggplot2
* palmerpenguins

For a refresher about how to install and load packages, see the
[Packages][r-basics-packages] section of DataLab's R Basics workshop reader.

[r-basics-packages]: https://ucdavisdatalab.github.io/dwr_workshop_r_basics/chapters/getting-started/getting-started.html#sec-packages
:::

Statistics help us make informed decisions about the world. Sometimes the goal
is to evaluate whether a particular belief or **hypothesis** is true. We can
weigh the evidence in a dataset for (or against) a hypothesis with a
statistical procedure called a **hypothesis test**. Hypothesis tests take many
forms and are often tailored to specific problems. Nonetheless, all hypothesis
tests are based on a general framework. This chapter introduces the hypothesis
testing framework as well as a specific kind of hypothesis test that's broadly
applicable because of its minimal assumptions.


## Forming Hypotheses

The first step in hypothesis testing is forming a suitable hypothesis. The best
time to come up with a hypothesis is before you collect the dataset you'll use
to evaluate it. If the dataset has already been collected, the best time is
*before* doing any exploration. This way the dataset serves as a fair,
independent sample for testing the hypothesis.

:::{.callout-warning}
When you form a hypothesis based on patterns you see in a dataset, no matter
how slight, using the same dataset to test the hypothesis will overstate the
strength of the evidence.

To test a hypothesis formed by exploring a dataset, you must collect an
entirely new dataset from the same population.
:::

Ideally, your hypothesis is based on a clear conceptual model rooted in
personal experience and expert knowledge about the topic. This knowledge may
include prior work with *other* datasets. A good way to check is to write an
explanation of your hypothesis and why you believe it might be true. Ask
yourself whether a peer would find your argument convincing enough to warrant
further investigation, and if not, adjust the hypothesis.

:::{.callout-important}
We form hypotheses about a population and use hypothesis tests to test them on
samples. If you can collect data for the entire population, there's no need to
conduct a hypothesis test---the sample statistics are the population
statistics!
:::

In order to test a hypothesis with data, there are two requirements. First, the
hypothesis must relate to something that can be measured. If you can't measure
it, you can't test it (although in some cases you can choose and test a proxy).
If you already have a dataset, make sure that its features allow asking the
kinds of questions you want to ask.

Second, the hypothesis must be specific and falsifiable. Data and statistics
can't help with a hypothesis that's too broad or impossible to disprove. Try to
translate your hypothesis into a statement about a population parameter.

As an example, suppose you study trout in California rivers. You suspect that
the trout population in one river increased over the past year. You're not able
to conduct a complete census of the trout population, so you collect counts at
specific locations and times. These counts are the feature you can use to
address the hypothesis. There are several ways to make the hypothesis specific
enough to test; a simple one is to ask whether the mean counts in the current
year (averaging over locations) are higher than the mean counts in the previous
year.

<!--
As an example, suppose you've developed a new medicine to lower blood pressure.
Naturally, your hypothesis is that people who take the medicine will have lower
blood pressure than people who don't, all other things being equal. When you
collect a dataset, you must measure blood pressure in order to be able to
conclude anything about the hypothesis. You can make the hypothesis more
specific by comparing the mean blood pressure of the two groups.
-->


## The Framework

Every hypothesis test consists of the following steps:

1. Describe the hypothesis in terms of two competing claims. The first, called
   the **null hypothesis**, should be a reasonable default or baseline. The
   second, called the **alternative hypothesis** should be the hypothesis you
   want to test. The null and alternative hypotheses must be mutually
   exclusive, meaning only one can possibly be true.

2. Identify a statistic related to the hypothesis with a known sampling
   distribution. Many hypothesis tests use the sample mean, since its
   distribution is well-understood. Compute the statistic on the sample.

3. Assume the null hypothesis is true. Use the sampling distribution to compute
   the probability of getting a statistic at least as unlikely as the sample
   statistic. For most hypothesis tests, we interpret "unlikely" as extreme
   (farther out in the distribution's tails). This probability, called a
   **p-value**, is a measure of evidence against the null hypothesis.

4. If the p-value is very small, the sample statistic is unlikely under the
   null hypothesis. In this case, we say that the result is **statistically
   discernable** and reject the null hypothesis. Otherwise, the sample
   statistic is compatible with the null hypothesis, so we do not reject it.

In step 4, the convention is to choose a specific threshhold for "very small,"
called the **discernibility level**. This is usually denoted by the Greek
letter $\alpha$ (alpha). The discernibility level is the approximate
probability of rejecting the null hypothesis when it's true (a false positive).
Most statistical software defaults to $\alpha = 0.05$ (5%), but you should
think carefully about what an acceptable false positive rate is for your work.

:::{.callout-important}
This framework only allows us to test whether the null hypothesis is unlikely!

A small p-value does not guarantee that the alternative hypothesis is correct
if multiple alternatives are possible. Along the same lines, a large p-value
does not guarantee that the null hypothesis is correct, nor that the
alternative hypothesis is incorrect.
:::

:::{.callout-note title="Note: Statistical Significance"}
"Statistically significant" is another term for for statistically discernable.
We prefer the latter, because somtimes a result is statistically discernable
but not important or meaningful in any real-world sense. Calling such a result
"significant" can easily give the wrong impression.
:::

:::{.callout-note title="Note: Power"}
After learning about the discernibility level, you might wonder: what about the
probability of failing to reject the null hypothesis when it's false (a false
negative)?

Statisticians usually denote this probability by the Greek letter $\beta$
(beta). Its inverse, $1 - \beta$, is called the **power** of the hypothesis
test. The power is the approximate probability that the test (correctly)
rejects the null hypothesis when it's false. Hypothesis tests are often
designed to maximize the power $1 - \beta$ for a given discernibility level
$\alpha$.

Power depends on the sampling distribution(s) under the alternative hypothesis.
It's usually impossible to compute the exact power of a test, because the
alternative hypothesis depends on unknown population parameters rather than
specifying them. That said, for many tests, we can estimate power by choosing
reasonably likely parameter estimates (for example, based on other data).

Power also depends on sample size. If you plan to collect a dataset and carry
out a hypothesis test, you should take power estimates into account when
selecting the sample size. An experiment that uses an underpowered hypothesis
test is a waste of resources.
:::


## Dataset: Palmer Penguins

![
  Artwork by [Allison Horst][horst].
](/images/applied-statistics/lter_penguins.png){#fig-penguins}

[horst]: https://allisonhorst.com/

As a source of examples, we'll use the [Palmer Penguins dataset][penguins],
which was collected by [Dr. Kristen Gorman][gorman] at [Palmer Station,
Antarctica][palmer]. [Alison Horst][horst] packaged the data for public use.
The package is called palmerpenguins.

[penguins]: https://allisonhorst.github.io/palmerpenguins/
[gorman]: https://www.uaf.edu/cfos/people/faculty/detail/kristen-gorman.php
[palmer]: https://pallter.marine.rutgers.edu/

:::{.callout-important}
Install the palmerpenguins package now if you didn't earlier.

Load the package with the `library` function to access the dataset, which is
called `penguins`.
:::

:::{.callout-warning}
In recent versions of R, the `penguins` dataset is built-in, but has slightly
different column names. If you want to follow along with this reader, make sure
to use the dataset from the package rather than the built-in dataset.
:::

The dataset consists of observations of 344 penguins from 3 different species:
[Adélie][], [Chinstrap][], and [Gentoo][]. The measurements include flipper
length, bill width, sex, and body mass.

[Adélie]: https://en.wikipedia.org/wiki/Ad%C3%A9lie_penguin
[Chinstrap]: https://en.wikipedia.org/wiki/Chinstrap_penguin
[Gentoo]: https://en.wikipedia.org/wiki/Gentoo_penguin


## Permutation Tests

Despite the name, the conclusion of a hypothesis test is not guaranteed to be
correct, and other sources of knowledge about the hypothesis should also be
taken into account.

